#1
print("Hello,World!")
#2
print("Monica!")
#3
print("My name is Monica")
print("My age is 27")
#4
name="Monica"
age=20
mark=75.7
is_married=True
print("Name :", name)
print("Age :", age)
print("Mark :", mark)
print("Married :", is_married)
#5
name="Monica"
age="27"
print(name,age)
#6
name="Monica"
age=27
print("My name is:", name)
print("My age is:", age)
#7
a=20
b=10
print("Additon is:", a+b)
print("Subtraction is:", a-b)
print("Multiplication is:", a*b)
print("Division is:", a/b)
#8
print("*")
print("**")
print("***")
print("****")
#9
name="Elon musk"
age=55
isStudent=False
print("Name:", name)
print("Age:", age)
print("Student:",isStudent)
name="Steve Jobs"
age+=1
isStudent=True
print("Name:", name)
print("Age:", age)
print("Student:", isStudent)
#11
name="Pravin"
age=25
dob="15/09/2000"
height=5.2
weight=45.5
degree="B.E. COMPUTER SCIENCE"
gender="Male"
print("Name of the candidate:", name)
print("Age:", age)
print("DOB:", dob)
print("Height:", height)
print("Weight:", weight)
print("Degree:", degree)
print("Gender:", gender)